### ISSUE TITLE
problems with php 7.2

### ISSUE THREAD

**Issue by juanluisrosaramos** [kariae/docker-php#1]
Hi!

I build your php architecture and I found problems with building the docker container of PHP-fpm. These problems are related to PHP 7.2 the last version as they did not include anymore mcrypt and also because fpm-alpine moved from openssl to libressl

As I need php 7.1 I changed the first file of your Dockerfile (for php.fmp) and everything worked smoothly

FROM php:7.1-fpm-alpine

Thank you very much for your work, Juan Luis

**Comment by kariae** [comment]
Hey Juan, you're right I fixed that, thanks, and sorry by the way for the late reply, I didn't receive notifications about issues.
