### ISSUE TITLE
Install symphony within docker container

### ISSUE THREAD

**Issue by yccheok** [kariae/docker-php#2]
Thank you for creating this project.

I saw your article at https://lekode.com/2017/06/01/a-symfony-development-environment-using-docker/

I'm some how confused on symfony installation step. You mentioned.

    symfony new sf_app
    cp sf_app/* ./app/
    rm -rf sf_app

Does it mean we need to run these steps in host machine? Can we do it all at once inside Dockerfile?

**Comment by kariae** [comment]
Hey @yccheok,

For Symfony 4, they changed a little bit the installation to use only Composer I think, the article was for the installation of the version 3.4, you can check more details [here](https://symfony.com/doc/current/setup.html), and [here](https://symfony.com/doc/3.4/setup.html).

The main issue with the installer of the version 3.4 was that it can't install Symfony in non-empty folder, so as a workaround I create a temporary Symfony project `sf_app`, copy its content in the `app` folder and remove the temporary folder.

You can run the installation process using `symfony` command directly from the host machine if you have the command installed in it (cause you don't need to install it in your container), or if you use the latest version of Symfony you can use directly composer in the container.
